### ISSUE TITLE
Can not run the sample until fix a little code in encoders.py

### ISSUE THREAD

**Issue by fs302** [williamleif/graphsage-simple#2]
Hi William,

I clone the code and try run_cora. At first the interpreter raise the dimension problem until I fix the code in encoders.py(line 39) from:

`neigh_feats = self.aggregator.forward(nodes, [self.adj_lists[node] for node in nodes], `

to 

`neigh_feats = self.aggregator.forward(nodes, [self.adj_lists[int(node)] for node in nodes], `

Then It works fine. I think it is a type issue. Hope it will be helpful for others.

**Comment by williamleif** [comment]
Thanks for pointing this out! The code worked as it was with my package versions (perhaps a pytorch version issue?) and with python2.7, but in any event I pushed that fix you mentioned since that doesn't break anything.
